# Configuración para despliegue en Netlify

[build]
  # Directorio que contiene los archivos estáticos a publicar
  publish = "/"
  # Comando de construcción (no es necesario para este proyecto)
  command = ""

# Redirecciones y reescrituras
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Encabezados personalizados para mejorar la seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
